### PR TITLE
Add test script for base vehicle

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What changes do you make in this PR?

* Please describe why you create this PR

Improving code test coverage

## Checklist

* [ ] I have merged the latest main branch into current branch.
* [ ] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
@lqy0057 Could you please help me test this script?

```bash
cd ~/pgdrive
python pgdrive/tests/test_vehicle/test_ego_vehicle.py
```

The test can be passed if line 45 and line 60 is commented as in the latest `pzh-egov-test` branch.

I an not sure the transformation relationship between real heading and vehicle.heading.

But I think that would be better if `v.heading` and `v.get_state()["heading"]` and the heading in `v.reset(heading=XX)` have same semantic.

Could you help me uncommented line 45 and line 60 and add two assertions on the heading?

**Comment by lqy0057** [comment]
> @lqy0057 Could you please help me test this script?
> 
> ```shell
> cd ~/pgdrive
> python pgdrive/tests/test_vehicle/test_ego_vehicle.py
> ```
> 
> The test can be passed if line 45 and line 60 is commented as in the latest `pzh-egov-test` branch.
> 
> I an not sure the transformation relationship between real heading and vehicle.heading.
> 
> But I think that would be better if `v.heading` and `v.get_state()["heading"]` and the heading in `v.reset(heading=XX)` have same semantic.
> 
> Could you help me uncommented line 45 and line 60 and add two assertions on the heading?

I fixed this problem, test failures are caused by:
(1) a coordinate **bug** in vehicle reset (line 45)
(2) incorrect heading unit (line 60)

**Comment by pengzhenghao** [comment]
Great! Is this PR ready now?

**Comment by lqy0057** [comment]
Now, I move the ```test_nan_speed.py``` to ```test_ego_vehicle.py```, and delete it.

**Comment by lqy0057** [comment]
> Great! Is this PR ready now?

Yeahhhh

**Comment by lqy0057** [comment]
> Great! Is this PR ready now?
Format and merger it after your review!

**Pull request merged**
