### PR TITLE
Fix model

### PR DESCRIPTION
**Pull request by lqy0057**
## What changes do you make in this PR?

#223 

## Checklist

* [x] I have merged the latest main branch into current branch.
* [x] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Review by pengzhenghao — APPROVED** [review]
LGTM

**Comment by pengzhenghao** [comment]
Please right a keyword like!!!

```
Close #XXXX
```

You only put a line `#XXX` there will not close the issue!

**Comment by pengzhenghao** [comment]
By the way, will that influence the performance of expert??

**Comment by pengzhenghao** [comment]
Can merge this PR after testing the performance of the expert. (Don't need to make modification on the expert, just testing.)

**Comment by lqy0057** [comment]
image
success rate 0.93 (30 episode)

**Pull request merged**
