### PR TITLE
Fix some todos

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What changes do you make in this PR?

* Please describe why you create this PR

1. Fix change friction envs now!

## Checklist

* [ ] I have merged the latest main branch into current branch.
* [ ] I have run `bash scripts/format.sh` before merging.
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by pengzhenghao** [comment]
@lqy0057 

In pgdrive_env, the back_vehicles and forward_vehicles is not compatible with multi agent now!
So the function `custom_info_callback` and `_overtake_stat` is not working properly now. Please take a look.

**Comment by pengzhenghao** [comment]
When you finished, just merge this PR.

**Comment by pengzhenghao** [comment]
Some old "vis_xxx" file use deprecated config like: "use_image"

for example in vis_highway_render.py

**Comment by lqy0057** [comment]
I have solved these things in MARL-env branch, and I have merged the latest main into this branch. All functions of single-agent are preserved in MARL-env. You can even turn on expert-takeover for all agents!

**Pull request merged**
